# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        BasketballBundle\Entity\User: bcrypt


    role_hierarchy:
        ROLE_ADMIN: [ROLE_MAIN_PAGE, ROLE_ADMIN_PANEL, ROLE_ALLOWED_TO_SWITCH]
        ROLE_USER: [ROLE_MAIN_PAGE]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: {class: BasketballBundle\Entity\User, property: login}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - BasketballBundle\Security\LoginFormAuthenticator

            logout:
                path: /logout
                target: /login

            # http://localhost:8000/success?_switch_user=miki - wpisujemy tu wartość property ustawioną w providers
            switch_user: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
